apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    name: postgres-db-service
    app: demo-voting-app
spec:
  selector:
    name: postgres-db-pod
    app: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432
  
  type: ClusterIP